import { mkdtemp, rm } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { afterEach, beforeEach, describe, expect, it } from 'vitest'
import { makeTestPluginDb, type TestPluginDb } from '@acorn/plugin-api/testkit'
import { AgentArtifactStore } from './artifactStore'
import { ProviderEventMaterializer } from './providerEventMaterializer'

let testDb: TestPluginDb
let dataDir: string
let artifacts: AgentArtifactStore
let materializer: ProviderEventMaterializer

beforeEach(async () => {
  testDb = makeTestPluginDb('agents')
  dataDir = await mkdtemp(join(tmpdir(), 'acorn-provider-artifacts-'))
  artifacts = new AgentArtifactStore(testDb.db, dataDir)
  materializer = new ProviderEventMaterializer(artifacts, [])
})

afterEach(async () => {
  testDb.cleanup()
  await rm(dataDir, { recursive: true, force: true })
})

describe('provider event materialization', () => {
  it('takes custody of generated bytes before emitting a durable artifact reference', async () => {
    const bytes = Uint8Array.from([0x89, 0x50, 0x4e, 0x47])
    const events = await materializer.map('session', 'turn', {
      type: 'generated_artifact',
      kind: 'file',
      title: 'Generated image.png',
      mediaType: 'image/png',
      bytes,
    })

    expect(events).toHaveLength(1)
    expect(events[0]).toMatchObject({
      type: 'artifact',
      kind: 'file',
      title: 'Generated image.png',
      mediaType: 'image/png',
      byteSize: bytes.byteLength,
    })
    if (events[0]?.type !== 'artifact') throw new Error('Expected an artifact event.')
    expect(Array.from((await artifacts.read(events[0].artifactId))?.bytes ?? [])).toEqual(Array.from(bytes))
  })

  it('refuses generated output beyond the provider artifact ceiling', async () => {
    const events = await materializer.map('session', 'turn', {
      type: 'generated_artifact',
      kind: 'file',
      title: 'Too large.png',
      mediaType: 'image/png',
      bytes: new Uint8Array(16 * 1024 * 1024 + 1),
    })

    expect(events).toEqual([{
      type: 'diagnostic',
      level: 'warning',
      message: 'The provider returned a generated artifact larger than 16 MiB.',
    }])
  })
})
