import { afterEach, expect, it, vi } from 'vitest'
const end = vi.fn()
vi.mock('@acorn/plugin-api/client', () => ({ telemetryFor: () => ({ startOperation: () => ({ traceId: 'trace', spanId: 'span', end }) }) }))
const { startAgentView } = await import('./agentTelemetry')
afterEach(() => { vi.clearAllMocks(); vi.unstubAllGlobals(); vi.useRealTimers() })
it('waits for content and two frames, then ends once', () => {
  vi.useFakeTimers()
  const frames: FrameRequestCallback[] = []
  vi.stubGlobal('requestAnimationFrame', (cb: FrameRequestCallback) => { frames.push(cb); return frames.length })
  vi.stubGlobal('cancelAnimationFrame', vi.fn())
  const view = startAgentView('agents.session.open')
  expect(end).not.toHaveBeenCalled()
  view.ready()
  view.ready()
  frames.shift()!(0)
  expect(end).not.toHaveBeenCalled()
  frames.shift()!(16)
  expect(end).toHaveBeenCalledExactlyOnceWith('ok', { outcome: 'ready' })
  view.dispose()
  vi.advanceTimersByTime(30_000)
  expect(end).toHaveBeenCalledOnce()
})
it.each(['error', 'cancelled', 'timeout'])('records %s instead of readiness', (outcome) => {
  vi.useFakeTimers()
  const view = startAgentView('agents.session.open')
  if (outcome === 'error') view.fail()
  if (outcome === 'cancelled') view.dispose()
  if (outcome === 'timeout') vi.advanceTimersByTime(30_000)
  view.ready()
  expect(end).toHaveBeenCalledExactlyOnceWith(outcome === 'cancelled' ? 'ok' : 'error', { outcome })
})
