import { defineConfig } from 'drizzle-kit'

// This plugin's own migration chain (docs/vNext/data.md § Plugin DBs). Generated by the workspace
// script `node scripts/db.mjs generate`, which discovers every package holding a drizzle.config.ts.
export default defineConfig({
  dialect: 'sqlite',
  schema: './src/node/schema.ts',
  out: './migrations',
})
