ALTER TABLE `repo_paths` ADD `setup_script` text;--> statement-breakpoint
ALTER TABLE `repo_paths` ADD `setup_script_trigger` text;--> statement-breakpoint
ALTER TABLE `repo_paths` ADD `dev_script` text;--> statement-breakpoint
ALTER TABLE `repo_paths` ADD `dev_restart_script` text;--> statement-breakpoint
ALTER TABLE `repo_paths` ADD `teardown_script` text;--> statement-breakpoint
ALTER TABLE `repo_paths` ADD `db_url_script` text;--> statement-breakpoint
ALTER TABLE `repo_paths` ADD `db_schema_mode` text;--> statement-breakpoint
ALTER TABLE `repo_paths` ADD `db_schema_value` text;--> statement-breakpoint
ALTER TABLE `repo_paths` ADD `preview_mode` text;--> statement-breakpoint
ALTER TABLE `repo_paths` ADD `preview_value` text;--> statement-breakpoint
ALTER TABLE `repo_paths` ADD `browser_rules` text;--> statement-breakpoint
ALTER TABLE `workspaces` DROP COLUMN `setup_script`;--> statement-breakpoint
ALTER TABLE `workspaces` DROP COLUMN `setup_script_trigger`;--> statement-breakpoint
ALTER TABLE `workspaces` DROP COLUMN `dev_script`;--> statement-breakpoint
ALTER TABLE `workspaces` DROP COLUMN `dev_restart_script`;--> statement-breakpoint
ALTER TABLE `workspaces` DROP COLUMN `teardown_script`;--> statement-breakpoint
ALTER TABLE `workspaces` DROP COLUMN `db_url_script`;--> statement-breakpoint
ALTER TABLE `workspaces` DROP COLUMN `db_schema_mode`;--> statement-breakpoint
ALTER TABLE `workspaces` DROP COLUMN `db_schema_value`;--> statement-breakpoint
ALTER TABLE `workspaces` DROP COLUMN `preview_mode`;--> statement-breakpoint
ALTER TABLE `workspaces` DROP COLUMN `preview_value`;--> statement-breakpoint
ALTER TABLE `workspaces` DROP COLUMN `browser_rules`;