import { z } from 'zod'
import { PageSchema } from '../../../core/shared/publicApi/primitives'
import {
  ActionJobsSchema,
  AutoMergeSchema,
  BranchListSchema,
  CommentSchema,
  CompareQuerySchema,
  CompareSchema,
  CreatePullSchema,
  DraftSchema,
  InlineReviewCommentSchema,
  JobLogSchema,
  LabelNameSchema,
  LabelSetSchema,
  MentionsQuerySchema,
  MentionsSchema,
  MergePullSchema,
  PatchBatchSchema,
  PullPrefetchSchema,
  PullCommentSchema,
  PullDetailSchema,
  PullFileSchema,
  PullFilesQuerySchema,
  PullParams,
  PullSchema,
  PullsQuerySchema,
  RepoParams,
  RepoSchema,
  RequestReviewerSchema,
  ReviewSubmissionSchema,
  ReviewerSetSchema,
  ThreadResolvedSchema,
  ViewedSchema,
} from '../../../core/shared/publicApi/github'
import { NO_CONTENT, defineEndpoint, type PluginApiContribution } from '../../../core/server/publicApi/defineEndpoint'
import type { GitHubPublicService } from './publicService'

// GitHub plugin public API (docs/public-api.md). Base /plugins/github. Reads project the
// local mirror; the core mutations (create PR, merge, comment, close, reopen) call GitHub with the
// stored credential. The remaining mutation catalog (reviews, labels, auto-merge, reviewers, viewed,
// Actions rerun) is not yet wired.

const PLUGIN = 'github'
const uid = (ctx: { actor: { principalId: string } }) => ctx.actor.principalId

export function buildGithubPublicApi(gh: GitHubPublicService): PluginApiContribution {
  return {
    pluginId: PLUGIN,
    endpoints: [
      defineEndpoint({
        operationId: 'github.repos.list',
        pluginId: PLUGIN,
        method: 'GET',
        path: '/repos',
        scope: 'read',
        risk: 'read',
        summary: 'List mirrored repositories',
        response: PageSchema(RepoSchema),
        handler: async (ctx) => ({ items: await gh.repos(uid(ctx)), nextCursor: null }),
      }),
      defineEndpoint({
        operationId: 'github.pulls.list',
        pluginId: PLUGIN,
        method: 'GET',
        path: '/repos/:owner/:repo/pulls',
        scope: 'read',
        risk: 'read',
        summary: 'List pull requests',
        params: RepoParams,
        query: PullsQuerySchema,
        response: PageSchema(PullSchema),
        handler: async (ctx, { params, query }) => {
          const items = await gh.pulls(uid(ctx), params.owner, params.repo, query.state)
          return { items: items.slice(0, query.limit), nextCursor: null }
        },
      }),
      defineEndpoint({
        operationId: 'github.pulls.get',
        pluginId: PLUGIN,
        method: 'GET',
        path: '/repos/:owner/:repo/pulls/:number',
        scope: 'read',
        risk: 'read',
        summary: 'Get a pull request detail',
        params: PullParams,
        response: PullDetailSchema,
        handler: (ctx, { params }) => gh.pullDetail(uid(ctx), params.owner, params.repo, params.number),
      }),
      defineEndpoint({
        operationId: 'github.pulls.files',
        pluginId: PLUGIN,
        method: 'GET',
        path: '/repos/:owner/:repo/pulls/:number/files',
        scope: 'read',
        risk: 'read',
        summary: 'List a pull request’s changed files',
        params: PullParams,
        query: PullFilesQuerySchema,
        response: PageSchema(PullFileSchema),
        handler: async (ctx, { params, query }) => {
          const items = await gh.pullFiles(uid(ctx), params.owner, params.repo, params.number, query.includePatch === 'true')
          return { items: items.slice(0, query.limit), nextCursor: null }
        },
      }),
      defineEndpoint({
        operationId: 'github.blobs.get',
        pluginId: PLUGIN,
        method: 'GET',
        path: '/repos/:owner/:repo/blobs/:sha',
        scope: 'read',
        risk: 'read',
        summary: 'Read a cached blob (max 5 MiB)',
        params: RepoParams.extend({ sha: z.string().min(1).max(100) }),
        response: z.strictObject({ text: z.string() }),
        handler: (_ctx, { params }) => gh.blob(params.sha),
      }),

      // ---- Mutations ----
      defineEndpoint({
        operationId: 'github.repos.refresh',
        pluginId: PLUGIN,
        method: 'POST',
        path: '/repos/refresh',
        scope: 'write', // consumes upstream quota + mutates the local mirror
        risk: 'write',
        summary: 'Refresh the repository mirror from GitHub',
        body: z.undefined(),
        response: z.strictObject({ items: z.array(RepoSchema) }),
        handler: async (ctx) => ({ items: await gh.refreshRepos(uid(ctx)) }),
      }),
      defineEndpoint({
        operationId: 'github.pulls.create',
        pluginId: PLUGIN,
        method: 'POST',
        path: '/repos/:owner/:repo/pulls',
        scope: 'write',
        risk: 'write',
        summary: 'Create a pull request',
        idempotency: 'required',
        params: RepoParams,
        body: CreatePullSchema,
        response: z.strictObject({ number: z.number().int().positive() }),
        status: 201,
        handler: (ctx, { params, body }) => gh.createPull(uid(ctx), params.owner, params.repo, body),
      }),
      defineEndpoint({
        operationId: 'github.pulls.merge',
        pluginId: PLUGIN,
        method: 'POST',
        path: '/repos/:owner/:repo/pulls/:number/merge',
        scope: 'write',
        risk: 'write',
        summary: 'Merge a pull request',
        idempotency: 'required',
        params: PullParams,
        body: MergePullSchema,
        response: z.strictObject({ state: z.literal('merged') }),
        handler: (ctx, { params, body }) => gh.merge(uid(ctx), params.owner, params.repo, params.number, body.method),
      }),
      defineEndpoint({
        operationId: 'github.pulls.comment',
        pluginId: PLUGIN,
        method: 'POST',
        path: '/repos/:owner/:repo/pulls/:number/comments',
        scope: 'write',
        risk: 'write',
        summary: 'Comment on a pull request',
        idempotency: 'required',
        params: PullParams,
        body: PullCommentSchema,
        response: CommentSchema,
        status: 201,
        handler: (ctx, { params, body }) => gh.comment(uid(ctx), params.owner, params.repo, params.number, body.body),
      }),
      defineEndpoint({
        operationId: 'github.pulls.close',
        pluginId: PLUGIN,
        method: 'POST',
        path: '/repos/:owner/:repo/pulls/:number/close',
        scope: 'write',
        risk: 'write',
        summary: 'Close a pull request',
        params: PullParams,
        body: z.undefined(),
        response: z.strictObject({ state: z.literal('closed') }),
        handler: async (ctx, { params }) => {
          await gh.setState(uid(ctx), params.owner, params.repo, params.number, 'closed')
          return { state: 'closed' as const }
        },
      }),
      defineEndpoint({
        operationId: 'github.pulls.reopen',
        pluginId: PLUGIN,
        method: 'POST',
        path: '/repos/:owner/:repo/pulls/:number/reopen',
        scope: 'write',
        risk: 'write',
        summary: 'Reopen a pull request',
        params: PullParams,
        body: z.undefined(),
        response: z.strictObject({ state: z.literal('open') }),
        handler: async (ctx, { params }) => {
          await gh.setState(uid(ctx), params.owner, params.repo, params.number, 'open')
          return { state: 'open' as const }
        },
      }),
      defineEndpoint({
        operationId: 'github.repos.labels',
        pluginId: PLUGIN,
        method: 'GET',
        path: '/repos/:owner/:repo/labels',
        scope: 'read',
        risk: 'read',
        summary: 'List repository labels',
        params: RepoParams,
        response: LabelSetSchema,
        handler: async (ctx, { params }) => ({ labels: await gh.repoLabels(uid(ctx), params.owner, params.repo) }),
      }),
      defineEndpoint({
        operationId: 'github.repos.branches',
        pluginId: PLUGIN,
        method: 'GET',
        path: '/repos/:owner/:repo/branches',
        scope: 'read',
        risk: 'read',
        summary: 'List branches',
        params: RepoParams,
        response: BranchListSchema,
        handler: async (ctx, { params }) => ({ items: await gh.branches(uid(ctx), params.owner, params.repo), nextCursor: null }),
      }),
      defineEndpoint({
        operationId: 'github.repos.mentions',
        pluginId: PLUGIN,
        method: 'GET',
        path: '/repos/:owner/:repo/mentions',
        scope: 'read',
        risk: 'read',
        summary: 'Login suggestions for mentions',
        params: RepoParams,
        query: MentionsQuerySchema,
        response: MentionsSchema,
        handler: async (ctx, { params, query }) => ({ items: await gh.mentions(uid(ctx), params.owner, params.repo, query.query) }),
      }),
      defineEndpoint({
        operationId: 'github.repos.compare',
        pluginId: PLUGIN,
        method: 'GET',
        path: '/repos/:owner/:repo/compare',
        scope: 'read',
        risk: 'read',
        summary: 'Compare two refs',
        params: RepoParams,
        query: CompareQuerySchema,
        response: CompareSchema,
        handler: (ctx, { params, query }) => gh.compare(uid(ctx), params.owner, params.repo, query.base, query.head),
      }),
      defineEndpoint({
        operationId: 'github.pulls.prefetch',
        pluginId: PLUGIN,
        method: 'POST',
        path: '/repos/:owner/:repo/pulls/prefetch',
        scope: 'read', // warms mirrored pull items; POST carries the batch
        risk: 'read',
        summary: 'Batch-warm pull items',
        params: RepoParams,
        body: PullPrefetchSchema,
        response: z.strictObject({ items: z.array(PullSchema) }),
        handler: async (ctx, { params, body }) => ({ items: await gh.prefetch(uid(ctx), params.owner, params.repo, body.numbers) }),
      }),
      defineEndpoint({
        operationId: 'github.pulls.files.batch',
        pluginId: PLUGIN,
        method: 'POST',
        path: '/repos/:owner/:repo/pulls/:number/files/batch',
        scope: 'read', // read even though POST carries the path list
        risk: 'read',
        summary: 'Fetch specific changed files',
        params: PullParams,
        body: PatchBatchSchema,
        response: z.strictObject({ items: z.array(PullFileSchema) }),
        handler: async (ctx, { params, body }) => ({ items: await gh.filesBatch(uid(ctx), params.owner, params.repo, params.number, body.paths) }),
      }),
      defineEndpoint({
        operationId: 'github.actions.jobs',
        pluginId: PLUGIN,
        method: 'GET',
        path: '/repos/:owner/:repo/actions/runs/:runId/jobs',
        scope: 'read',
        risk: 'read',
        summary: 'List a workflow run’s jobs + steps',
        params: RepoParams.extend({ runId: z.coerce.number().int().positive() }),
        response: ActionJobsSchema,
        handler: (ctx, { params }) => gh.actionsJobs(uid(ctx), params.owner, params.repo, params.runId),
      }),
      defineEndpoint({
        operationId: 'github.actions.job-log',
        pluginId: PLUGIN,
        method: 'GET',
        path: '/repos/:owner/:repo/actions/jobs/:jobId/log',
        scope: 'read',
        risk: 'read',
        summary: 'Bounded job log',
        params: RepoParams.extend({ jobId: z.coerce.number().int().positive() }),
        response: JobLogSchema,
        handler: (ctx, { params }) => gh.jobLog(uid(ctx), params.owner, params.repo, params.jobId),
      }),
      defineEndpoint({
        operationId: 'github.pulls.draft',
        pluginId: PLUGIN,
        method: 'PUT',
        path: '/repos/:owner/:repo/pulls/:number/draft',
        scope: 'write',
        risk: 'write',
        summary: 'Set draft state',
        params: PullParams,
        body: DraftSchema,
        response: DraftSchema,
        handler: (ctx, { params, body }) => gh.setDraft(uid(ctx), params.owner, params.repo, params.number, body.draft),
      }),
      defineEndpoint({
        operationId: 'github.pulls.auto-merge.enable',
        pluginId: PLUGIN,
        method: 'PUT',
        path: '/repos/:owner/:repo/pulls/:number/auto-merge',
        scope: 'write',
        risk: 'write',
        summary: 'Enable auto-merge',
        idempotency: 'required',
        params: PullParams,
        body: AutoMergeSchema,
        response: z.strictObject({ autoMergeEnabled: z.literal(true) }),
        handler: (ctx, { params, body }) => gh.enableAutoMerge(uid(ctx), params.owner, params.repo, params.number, body.method),
      }),
      defineEndpoint({
        operationId: 'github.pulls.auto-merge.disable',
        pluginId: PLUGIN,
        method: 'DELETE',
        path: '/repos/:owner/:repo/pulls/:number/auto-merge',
        scope: 'write',
        risk: 'write',
        summary: 'Disable auto-merge',
        params: PullParams,
        response: z.undefined(),
        status: 204,
        handler: async (ctx, { params }) => {
          await gh.disableAutoMerge(uid(ctx), params.owner, params.repo, params.number)
          return NO_CONTENT
        },
      }),
      defineEndpoint({
        operationId: 'github.pulls.labels.add',
        pluginId: PLUGIN,
        method: 'POST',
        path: '/repos/:owner/:repo/pulls/:number/labels',
        scope: 'write',
        risk: 'write',
        summary: 'Add a label',
        params: PullParams,
        body: LabelNameSchema,
        response: LabelSetSchema,
        handler: async (ctx, { params, body }) => ({ labels: await gh.labels(uid(ctx), params.owner, params.repo, params.number, 'add', body.name) }),
      }),
      defineEndpoint({
        operationId: 'github.pulls.labels.remove',
        pluginId: PLUGIN,
        method: 'DELETE',
        path: '/repos/:owner/:repo/pulls/:number/labels/:name',
        scope: 'write',
        risk: 'write',
        summary: 'Remove a label',
        params: PullParams.extend({ name: z.string().min(1).max(200) }),
        response: LabelSetSchema,
        handler: async (ctx, { params }) => ({ labels: await gh.labels(uid(ctx), params.owner, params.repo, params.number, 'remove', params.name) }),
      }),
      defineEndpoint({
        operationId: 'github.pulls.files.viewed',
        pluginId: PLUGIN,
        method: 'PUT',
        path: '/repos/:owner/:repo/pulls/:number/files/viewed',
        scope: 'write',
        risk: 'write',
        summary: 'Mark a changed file viewed',
        params: PullParams,
        body: ViewedSchema,
        response: ViewedSchema,
        handler: (ctx, { params, body }) => gh.setViewed(uid(ctx), params.owner, params.repo, params.number, body.path, body.viewed),
      }),
      defineEndpoint({
        operationId: 'github.pulls.review-comments.create',
        pluginId: PLUGIN,
        method: 'POST',
        path: '/repos/:owner/:repo/pulls/:number/review-comments',
        scope: 'write',
        risk: 'write',
        summary: 'Start an inline review comment',
        idempotency: 'required',
        params: PullParams,
        body: InlineReviewCommentSchema,
        response: z.strictObject({ created: z.literal(true) }),
        status: 201,
        handler: (ctx, { params, body }) => gh.reviewComment(uid(ctx), params.owner, params.repo, params.number, body),
      }),
      defineEndpoint({
        operationId: 'github.pulls.review-comments.reply',
        pluginId: PLUGIN,
        method: 'POST',
        path: '/repos/:owner/:repo/pulls/:number/review-comments/:commentId/replies',
        scope: 'write',
        risk: 'write',
        summary: 'Reply to a review thread',
        idempotency: 'required',
        params: PullParams.extend({ commentId: z.string().min(1).max(100) }),
        body: PullCommentSchema,
        response: z.strictObject({ created: z.literal(true) }),
        status: 201,
        handler: (ctx, { params, body }) => gh.reviewReply(uid(ctx), params.owner, params.repo, params.number, params.commentId, body.body),
      }),
      defineEndpoint({
        operationId: 'github.pulls.threads.resolved',
        pluginId: PLUGIN,
        method: 'PUT',
        path: '/repos/:owner/:repo/pulls/:number/threads/:threadId/resolved',
        scope: 'write',
        risk: 'write',
        summary: 'Resolve or unresolve a review thread',
        params: PullParams.extend({ threadId: z.string().min(1).max(200) }),
        body: ThreadResolvedSchema,
        response: ThreadResolvedSchema,
        handler: (ctx, { params, body }) => gh.setThreadResolved(uid(ctx), params.threadId, body.resolved),
      }),
      defineEndpoint({
        operationId: 'github.pulls.reviews.submit',
        pluginId: PLUGIN,
        method: 'POST',
        path: '/repos/:owner/:repo/pulls/:number/reviews',
        scope: 'write',
        risk: 'write',
        summary: 'Submit a pull request review',
        idempotency: 'required',
        params: PullParams,
        body: ReviewSubmissionSchema,
        response: z.strictObject({ submitted: z.literal(true) }),
        status: 201,
        handler: (ctx, { params, body }) => gh.submitReview(uid(ctx), params.owner, params.repo, params.number, body.event, body.body),
      }),
      defineEndpoint({
        operationId: 'github.pulls.reviewers.add',
        pluginId: PLUGIN,
        method: 'POST',
        path: '/repos/:owner/:repo/pulls/:number/requested-reviewers',
        scope: 'write',
        risk: 'write',
        summary: 'Request a reviewer',
        params: PullParams,
        body: RequestReviewerSchema,
        response: ReviewerSetSchema,
        handler: (ctx, { params, body }) => gh.requestedReviewers(uid(ctx), params.owner, params.repo, params.number, 'add', body.login),
      }),
      defineEndpoint({
        operationId: 'github.pulls.reviewers.remove',
        pluginId: PLUGIN,
        method: 'DELETE',
        path: '/repos/:owner/:repo/pulls/:number/requested-reviewers/:login',
        scope: 'write',
        risk: 'write',
        summary: 'Remove a requested reviewer',
        params: PullParams.extend({ login: z.string().min(1).max(100) }),
        response: ReviewerSetSchema,
        handler: (ctx, { params }) => gh.requestedReviewers(uid(ctx), params.owner, params.repo, params.number, 'remove', params.login),
      }),
      defineEndpoint({
        operationId: 'github.actions.rerun-failed',
        pluginId: PLUGIN,
        method: 'POST',
        path: '/repos/:owner/:repo/actions/runs/:runId/rerun-failed',
        scope: 'write',
        risk: 'write',
        summary: 'Rerun a workflow run’s failed jobs',
        params: RepoParams.extend({ runId: z.coerce.number().int().positive() }),
        body: z.undefined(),
        response: z.strictObject({ accepted: z.literal(true) }),
        handler: (ctx, { params }) => gh.rerunFailed(uid(ctx), params.owner, params.repo, params.runId),
      }),
    ],
  }
}
