// Stable TUI kit entrypoint. Components live beside the behavior they own.
export { Card, Fold, Inline, Section, Stack, Toolbar, ToolbarSpacer } from './grouping/blocks'
export { Timeline } from './grouping/timeline'
export { panelsFor, registerPanel } from './grouping/panelRegistry'
export { DocumentTabs, TabPanel, Tabs } from './grouping/tabs'
export { Modal, ModalActions, ModalBody } from './grouping/modal'
export { Menu } from './grouping/menu'
export { Popover } from './grouping/popover'
export { DetailColumn, ListColumn, ListDetail, SplitHandle } from './grouping/columns'
export { SectionHeader, Sections } from './grouping/sections'
export { SettingRow, SettingsSection } from './grouping/settings'
