import { z } from 'zod'
import { IdSchema } from '../../../core/shared/publicApi/primitives'
import {
  AgentSendResultSchema,
  CreateExecutionSchema,
  CreateTerminalSessionSchema,
  DeleteSessionQuerySchema,
  ExecutionQuerySchema,
  ExecutionSchema,
  McpInspectSchema,
  McpStarterResultSchema,
  PutRepoPathSchema,
  PutRunTargetsSchema,
  RepoPathSchema,
  ResizeTerminalSchema,
  SendToAgentSchema,
  SessionsQuerySchema,
  TerminalProfileSchema,
  TerminalSessionSchema,
  WorktreeRemoveQuerySchema,
  WorktreeStatusSchema,
} from '../../../core/shared/publicApi/terminal'
import { OwnerSchema, PageSchema, RepoNameSchema } from '../../../core/shared/publicApi/primitives'
import { NO_CONTENT, defineEndpoint, type PluginApiContribution } from '../../../core/server/publicApi/defineEndpoint'
import type { SendSubmit } from '../server/routes/terminal'
import type { RepoCheckoutService } from '../main/checkoutService'
import type { CommandExecutionService } from '../main/executionService'
import type { TerminalProfilesService } from '../main/profilesService'
import type { TerminalSessionService } from '../main/sessionService'
import type { WorktreeService } from '../main/worktreeService'

// Terminal plugin public API (docs/public-api.md). Base /plugins/terminal.
// Captured executions + worktree lifecycle. Interactive sessions + PTY streaming and run-targets are
// a separate, still-to-land surface.

const PLUGIN = 'terminal'
const TaskParams = z.strictObject({ taskId: IdSchema })

const RepoParams = z.strictObject({ owner: OwnerSchema, repo: RepoNameSchema })

// (mcp endpoints reuse TaskParams)
const SessionParams = z.strictObject({ sessionId: IdSchema })

export function buildTerminalPublicApi(
  executions: CommandExecutionService,
  worktrees: WorktreeService,
  checkout: RepoCheckoutService,
  profiles: TerminalProfilesService,
  sessions: TerminalSessionService,
): PluginApiContribution {
  return {
    pluginId: PLUGIN,
    endpoints: [
      defineEndpoint({
        operationId: 'terminal.sessions.list',
        pluginId: PLUGIN,
        method: 'GET',
        path: '/sessions',
        scope: 'read',
        risk: 'read',
        summary: 'List terminal sessions',
        query: SessionsQuerySchema,
        response: PageSchema(TerminalSessionSchema),
        handler: async (_ctx, { query }) => ({ items: await sessions.list(query), nextCursor: null }),
      }),
      defineEndpoint({
        operationId: 'terminal.sessions.create',
        pluginId: PLUGIN,
        method: 'POST',
        path: '/tasks/:taskId/sessions',
        scope: 'write',
        risk: 'execute',
        summary: 'Create a terminal session',
        idempotency: 'required',
        params: TaskParams,
        body: CreateTerminalSessionSchema,
        response: TerminalSessionSchema,
        status: 201,
        handler: (_ctx, { params, body }) => sessions.create(params.taskId, body),
      }),
      defineEndpoint({
        operationId: 'terminal.sessions.get',
        pluginId: PLUGIN,
        method: 'GET',
        path: '/sessions/:sessionId',
        scope: 'read',
        risk: 'read',
        summary: 'Get a terminal session',
        params: SessionParams,
        response: TerminalSessionSchema,
        handler: (_ctx, { params }) => sessions.get(params.sessionId),
      }),
      defineEndpoint({
        operationId: 'terminal.sessions.interrupt',
        pluginId: PLUGIN,
        method: 'POST',
        path: '/sessions/:sessionId/interrupt',
        scope: 'write',
        risk: 'execute',
        summary: 'Interrupt (Ctrl-C) a session',
        params: SessionParams,
        body: z.undefined(),
        response: TerminalSessionSchema,
        handler: (_ctx, { params }) => sessions.interrupt(params.sessionId),
      }),
      defineEndpoint({
        operationId: 'terminal.sessions.kill',
        pluginId: PLUGIN,
        method: 'POST',
        path: '/sessions/:sessionId/kill',
        scope: 'write',
        risk: 'execute',
        summary: 'Kill a session',
        params: SessionParams,
        body: z.undefined(),
        response: TerminalSessionSchema,
        handler: (_ctx, { params }) => sessions.kill(params.sessionId),
      }),
      defineEndpoint({
        operationId: 'terminal.sessions.delete',
        pluginId: PLUGIN,
        method: 'DELETE',
        path: '/sessions/:sessionId',
        scope: 'write',
        risk: 'execute',
        summary: 'Remove a session',
        params: SessionParams,
        query: DeleteSessionQuerySchema,
        response: z.undefined(),
        status: 204,
        handler: async (_ctx, { params, query }) => {
          await sessions.remove(params.sessionId, query.force === 'true')
          return NO_CONTENT
        },
      }),
      defineEndpoint({
        operationId: 'terminal.sessions.resize',
        pluginId: PLUGIN,
        method: 'POST',
        path: '/sessions/:sessionId/resize',
        scope: 'write',
        risk: 'execute',
        summary: 'Resize a session',
        params: SessionParams,
        body: ResizeTerminalSchema,
        response: TerminalSessionSchema,
        handler: (_ctx, { params, body }) => sessions.resize(params.sessionId, body.cols, body.rows),
      }),
      defineEndpoint({
        operationId: 'terminal.sessions.send',
        pluginId: PLUGIN,
        method: 'POST',
        path: '/sessions/:sessionId/send',
        scope: 'write',
        risk: 'execute',
        summary: 'Send agent input',
        params: SessionParams,
        body: SendToAgentSchema,
        response: AgentSendResultSchema,
        handler: (_ctx, { params, body }) => sessions.send(params.sessionId, body.text, body.submit as SendSubmit),
      }),
      defineEndpoint({
        operationId: 'terminal.mcp.inspect',
        pluginId: PLUGIN,
        method: 'GET',
        path: '/tasks/:taskId/mcp',
        scope: 'read',
        risk: 'read',
        summary: 'Inspect MCP config (no secret values)',
        params: TaskParams,
        response: McpInspectSchema,
        handler: (_ctx, { params }) => sessions.mcpInspect(params.taskId),
      }),
      defineEndpoint({
        operationId: 'terminal.mcp.starter',
        pluginId: PLUGIN,
        method: 'POST',
        path: '/tasks/:taskId/mcp/starter',
        scope: 'write',
        risk: 'write',
        summary: 'Create an MCP starter file',
        params: TaskParams,
        body: z.undefined(),
        response: McpStarterResultSchema,
        handler: (_ctx, { params }) => sessions.mcpStarter(params.taskId),
      }),
      defineEndpoint({
        operationId: 'terminal.profiles.list',
        pluginId: PLUGIN,
        method: 'GET',
        path: '/profiles',
        scope: 'read',
        risk: 'read',
        summary: 'List terminal profiles + availability',
        response: z.strictObject({ items: z.array(TerminalProfileSchema) }),
        handler: async () => ({ items: await profiles.list() }),
      }),
      defineEndpoint({
        operationId: 'terminal.checkout.get',
        pluginId: PLUGIN,
        method: 'GET',
        path: '/repositories/:owner/:repo/checkout',
        scope: 'read',
        risk: 'read',
        summary: 'Local checkout mapping for a repository',
        params: RepoParams,
        response: RepoPathSchema,
        handler: (_ctx, { params }) => checkout.get(params.owner, params.repo),
      }),
      defineEndpoint({
        operationId: 'terminal.checkout.set',
        pluginId: PLUGIN,
        method: 'PUT',
        path: '/repositories/:owner/:repo/checkout',
        scope: 'write',
        risk: 'write',
        summary: 'Map a local checkout to a repository',
        params: RepoParams,
        body: PutRepoPathSchema,
        response: RepoPathSchema,
        handler: (_ctx, { params, body }) => checkout.setPath(params.owner, params.repo, body.path),
      }),
      defineEndpoint({
        operationId: 'terminal.checkout.run-targets',
        pluginId: PLUGIN,
        method: 'PUT',
        path: '/repositories/:owner/:repo/run-targets',
        scope: 'write',
        risk: 'write',
        summary: 'Replace a repository’s run targets',
        params: RepoParams,
        body: PutRunTargetsSchema,
        response: RepoPathSchema,
        handler: (_ctx, { params, body }) => checkout.setRunTargets(params.owner, params.repo, body.runTargets),
      }),
      defineEndpoint({
        operationId: 'terminal.worktree.status',
        pluginId: PLUGIN,
        method: 'GET',
        path: '/tasks/:taskId/worktree',
        scope: 'read',
        risk: 'read',
        summary: 'Task worktree status',
        params: TaskParams,
        response: WorktreeStatusSchema,
        handler: (_ctx, { params }) => worktrees.status(params.taskId),
      }),
      defineEndpoint({
        operationId: 'terminal.worktree.create',
        pluginId: PLUGIN,
        method: 'POST',
        path: '/tasks/:taskId/worktree/create',
        scope: 'write',
        risk: 'execute',
        summary: 'Create the task worktree',
        params: TaskParams,
        body: z.undefined(),
        response: WorktreeStatusSchema,
        handler: (_ctx, { params }) => worktrees.create(params.taskId),
      }),
      defineEndpoint({
        operationId: 'terminal.worktree.adopt-checkout',
        pluginId: PLUGIN,
        method: 'POST',
        path: '/tasks/:taskId/worktree/adopt-checkout',
        scope: 'write',
        risk: 'execute',
        summary: 'Adopt the repo’s current checkout as the task worktree',
        params: TaskParams,
        body: z.undefined(),
        response: WorktreeStatusSchema.extend({ branch: z.string().nullable() }),
        handler: (_ctx, { params }) => worktrees.adoptCheckout(params.taskId),
      }),
      defineEndpoint({
        operationId: 'terminal.worktree.delete',
        pluginId: PLUGIN,
        method: 'DELETE',
        path: '/tasks/:taskId/worktree',
        scope: 'write',
        risk: 'execute',
        summary: 'Remove the task worktree',
        params: TaskParams,
        query: WorktreeRemoveQuerySchema,
        response: z.undefined(),
        status: 204,
        handler: async (_ctx, { params, query }) => {
          await worktrees.remove(params.taskId, query.force === 'true')
          return NO_CONTENT
        },
      }),
      defineEndpoint({
        operationId: 'terminal.executions.create',
        pluginId: PLUGIN,
        method: 'POST',
        path: '/tasks/:taskId/executions',
        scope: 'write',
        risk: 'execute',
        summary: 'Run a captured command in the task worktree',
        idempotency: 'required',
        params: z.strictObject({ taskId: IdSchema }),
        body: CreateExecutionSchema,
        response: ExecutionSchema,
        status: 202,
        handler: (_ctx, { params, body }) => executions.create(params.taskId, body),
      }),
      defineEndpoint({
        operationId: 'terminal.executions.get',
        pluginId: PLUGIN,
        method: 'GET',
        path: '/executions/:executionId',
        scope: 'read',
        risk: 'read',
        summary: 'Get a captured execution',
        params: z.strictObject({ executionId: IdSchema }),
        query: ExecutionQuerySchema,
        response: ExecutionSchema,
        handler: (_ctx, { params, query }) => executions.get(params.executionId, query.includeOutput === 'true'),
      }),
      defineEndpoint({
        operationId: 'terminal.executions.cancel',
        pluginId: PLUGIN,
        method: 'POST',
        path: '/executions/:executionId/cancel',
        scope: 'write',
        risk: 'execute',
        summary: 'Cancel a running execution',
        params: z.strictObject({ executionId: IdSchema }),
        body: z.undefined(),
        response: ExecutionSchema,
        handler: (_ctx, { params }) => executions.cancel(params.executionId),
      }),
    ],
  }
}
