import { ACORN_BASELINE } from '@acorn/protocol/baseline.ts'

// --- 4. the two shapes no description states ---

export const SECTION_CONTRACTS = [
  '## 4. Two shapes nothing else tells you',
  '',
  '### Structured plans and For each',
  '',
  'Use an agent step with an object schema containing an items array. Every item has a stable key.',
  'Follow it with workflow-map (For each), items: { step: "plan", pointer: "/items" }, itemKey: "/id".',
  'For separate sessions in the parent task, set agent: { prompt: "Fix the current item and verify the result." }.',
  'For child workflows, choose childWorkflow.ref from the available workflow catalog and bind each typed item to its declared inputs.',
  'Do not invent a child reference. Use an item agent when the request asks to run an agent for each item.',
  'An empty array succeeds without tasks. For each returns ordered children; ordinary graph convergence uses after edges.',
  '',
  '### The branches a decide takes',
  '',
  '`decide` asks an agent for one verdict and takes the branch matching it.',
  '',
  '{',
  '  "id": "triage",',
  '  "name": "triage",',
  '  "kind": "decide",',
  '  "after": ["reproduce"],',
  '  "prompt": "Read the reproduction above. Answer with a verdict of either code, for a defect in this repository, or data, for bad data in the environment.",',
  '  "branches": { "code": "write-the-fix", "data": "fix-the-data", "default": "ask-a-person" }',
  '}',
  '',
  '- The default schema asks for one string field called `verdict`. The keys of `branches` are the',
  '  verdicts, so the prompt has to name the same words.',
  '- Every branch target must wait for the decision. Give each target an `after` naming the decide',
  '  step, or naming a step that already waits for it.',
  '- A verdict matching no key fails the run, unless `branches` holds a key literally called',
  '  `default`. Add one whenever the prompt could produce a word you did not list.',
  '- When the verdict picks a target, every other target is marked skipped, and so is every step that',
  '  can only be reached through one of them. A step a live branch also reaches still runs.',
  '- Give each verdict its own step. Two verdicts pointing at one step means one of them was never a',
  '  real branch. `default` is the exception: pointing it at a step a listed verdict already uses is',
  '  how you say "treat anything else like that one".',
  '- Never put the step that follows the branches in `branches`. Put that work after them, with an',
  '  `after` naming every branch, and it runs whichever way the verdict went.',
].join('\n')

// --- 7. the checker, and the mistake this feature exists to avoid ---

export const SECTION_RULES = [
  '## 7. Rules and mistakes',
  '',
  '### What the checker refuses',
  '',
  'Every definition is checked before it runs. These are errors:',
  '',
  '- A step with no name, or a name used twice.',
  '- An `after` naming a step that does not exist, or naming the step itself.',
  '- A cycle.',
  '- A `kind` that section 3 does not list.',
  '- A `${steps.x.output}` reference to a step that is not behind this one, or a malformed token.',
  '- A `${inputs.x}` reference to an input that is not declared.',
  '- A step `tools.maxRisk` looser than the workflow ceiling.',
  '- An autonomous workflow with no `tools.maxRisk`.',
  '- A `decide` step with no `branches`, or a branch target that does not wait for the decision.',
  '- A required field of a kind left empty.',
  '- `isolation` or `inputs` on a kind that does not run an agent.',
  '- A child workflow reference that section 6 does not list.',
  '- A child input binding the target does not declare, or a required child input with no binding.',
  '- A map source or step binding that does not name a structured predecessor.',
  '',
  '### Mistakes to avoid',
  '',
  '- Writing a chain when the description says two things happen at once. Give both steps the same',
  '  `after`.',
  '- Writing a `with` object on a built-in kind. Built-ins take named keys.',
  '- Writing named keys on a contributed kind. Everything it takes goes in `with`.',
  '- Naming a step in a prompt without putting it in `after`.',
  '- Giving a decide branch target no `after` of its own, so it starts beside the decision rather',
  '  than after it.',
  '- Leaving out a `default` branch when the verdict could be a word you did not list.',
  '- A For each without a stable item key, or without an agent or available child workflow.',
  '- An AI plan without a structural schema or stable item key. Empty arrays are valid.',
  '- A dash in an input name, or a digit at the front of one. An input name starts with a letter and',
  '  then takes letters, digits and underscores. Stable step IDs may also contain colons and dashes.',
  '- A missing, repeated, or unstable step id. Human step names may contain spaces.',
  '- An autonomous workflow with no `tools.maxRisk`.',
  '- Inventing a kind, a policy or a profile. Sections 3 and 5 list what exists.',
  '',
  '### One wrong answer, and the fix',
  '',
  'Asked for two agents investigating one issue at the same time and a third reading both:',
  '',
  'Wrong. Nothing runs at the same time. A step with no `after` waits for the step written before it,',
  'so this is a three-step chain:',
  '',
  '{',
  `  "baseline": "${ACORN_BASELINE}",`,
  '  "formatVersion": 1,',
  '  "name": "Investigate",',
  '  "steps": [',
  '    { "id": "check-the-logs", "name": "Check the logs", "prompt": "Read the logs for this failure and say what they show." },',
  '    { "id": "read-the-code", "name": "Read the code", "prompt": "Find the code behind this failure and say what looks wrong." },',
  '    { "id": "write-it-up", "name": "Write it up", "prompt": "Write the diagnosis." }',
  '  ]',
  '}',
  '',
  'Right. Two roots, then a fan-in that reads both. `write-it-up` needs no references, because',
  '`inputs` defaults to `append`:',
  '',
  '{',
  `  "baseline": "${ACORN_BASELINE}",`,
  '  "formatVersion": 1,',
  '  "name": "Investigate",',
  '  "steps": [',
  '    { "id": "check-the-logs", "name": "Check the logs", "after": [], "prompt": "Read the logs for this failure and say what they show." },',
  '    { "id": "read-the-code", "name": "Read the code", "after": [], "prompt": "Find the code behind this failure and say what looks wrong." },',
  '    { "id": "write-it-up", "name": "Write it up", "after": ["check-the-logs", "read-the-code"], "prompt": "A log reading and a code reading of one failure follow. Write the diagnosis: what is broken, why, and the smallest change that fixes it." }',
  '  ]',
  '}',
].join('\n')
