import { createSignal } from 'solid-js'
import eager from './iconNodes.eager.json'

// lucide-static's icon geometry, in two halves: the names this tree spells, carried by the chunk that
// draws them, and the other 1,669 behind a dynamic import.
//
// Why it is split at all: `Icon` resolves `props.name` against this map at render time, so the bundler
// cannot see which names are reachable and used to put all 706 KB in a startup chunk (371 KB minified,
// a quarter of the renderer's whole startup budget). Dropping the unreachable names is not available —
// a person can assign any of the 1,756 to a task and a plugin manifest can name any one, and both
// choices are persisted (docs/performance.md § Dropping unreferenced icons). So the
// bytes move rather than go.
//
// iconNodes.eager.json is generated by ../../../scripts/icon-census.mjs, which this package's `lint`
// re-runs in `--check` mode. A literal icon name added to the tree and not to that file fails the
// check, because it would otherwise render as its own text until the lazy half arrived.
//
// This was an ambient `declare module 'lucide-static/icon-nodes.json'` in a .d.ts. Ambient declarations
// only apply to programs that include the declaring file, so once client-core became its own package
// the declaration was invisible to every consumer compiling client-core's source. An ordinary module
// travels with the import graph instead.
//
// No import attribute on either import, and that is not an oversight: the TypeScript transform drops
// `with { type: 'json' }` before the bundler sees it, so writing one changes no output anywhere. The one
// host that cannot draw any of this swaps both files out (apps/tui/vite.config.ts § lucide-static).
//
// `[tag, attrs]` pairs: lucide uses path, circle, rect, polyline, line, ellipse and polygon.
export type IconNode = [string, Record<string, string>]
export type IconNodeMap = Record<string, IconNode[]>

export const eagerIconNodes = eager as unknown as IconNodeMap

// The full map, once it has arrived. A signal rather than a plain variable because `Icon` reads it
// inside its render: a name in the lazy half draws the glyph fallback, and this is what turns it into
// an SVG when the map lands.
const [loaded, setLoaded] = createSignal<IconNodeMap | null>(null)
let inFlight: Promise<IconNodeMap> | null = null

/** Fetch the full icon set. Idempotent, and the promise is shared, so many callers cost one request. */
export function loadIconNodes(): Promise<IconNodeMap> {
  const already = loaded()
  if (already) return Promise.resolve(already)
  inFlight ??= import('lucide-static/icon-nodes.json').then((module) => {
    // Eager first in the spread so the two halves cannot disagree about a name, whichever way the
    // census moved.
    const map: IconNodeMap = { ...(module.default as unknown as IconNodeMap), ...eagerIconNodes }
    setLoaded(map)
    return map
  })
  return inFlight
}

// A name worth fetching 706 KB for. `Icon` renders an unmatched name as text on purpose — Lucide has no
// brand icons, so provider marks and about 120 inline glyph literals across plugins/ rely on that
// fallback (docs/ui-design.md § Icons). Those are emoji, single characters and words with capitals or
// colons in them; asking Lucide about one would fetch the whole set to learn it was never there.
const LUCIDE_SHAPED = /^[a-z0-9][a-z0-9-]*$/

/**
 * The geometry for one icon name, or undefined. Reactive: a name only the lazy half has returns
 * undefined and starts the fetch, then resolves once the map arrives.
 */
export function iconNode(name: string): IconNode[] | undefined {
  const hit = eagerIconNodes[name]
  if (hit) return hit
  const map = loaded()
  if (map) return map[name]
  if (LUCIDE_SHAPED.test(name)) void loadIconNodes()
  return undefined
}

// Memoized on the map's identity rather than recomputed, because 1,756 keys per call would be paid on
// every keystroke in IconPicker's filter.
let namesOf: IconNodeMap | null = null
let namesCache: readonly string[] = []

/**
 * Every name that can be drawn right now: the eager set until the full map arrives, all of it after.
 * Reactive, so a consumer that called `loadIconNodes()` re-renders with the whole list.
 */
export function iconNames(): readonly string[] {
  const map = loaded() ?? eagerIconNodes
  if (namesOf !== map) {
    namesOf = map
    namesCache = Object.keys(map)
  }
  return namesCache
}
