import { z } from 'zod'
import { IdSchema, PageSchema } from '../../../core/shared/publicApi/primitives'
import { defineEndpoint, defineEvent, type PluginApiContribution } from '../../../core/server/publicApi/defineEndpoint'
import type { ManagedAgentRuntime } from '../main/runtime'
import { agentInputPartSchema } from '../shared/schemas'
import {
  PublicAgentEventSchema,
  PublicAgentArtifactSchema,
  PublicAgentProviderSchema,
  PublicAgentRequestSchema,
  PublicAgentSessionSchema,
  PublicAgentSnapshotSchema,
  PublicAgentTurnSchema,
  PublicCreateAgentSessionSchema,
  PublicEnqueueAgentTurnSchema,
} from '../shared/publicApi'

const PLUGIN = 'agents'
const TaskParams = z.strictObject({ taskId: IdSchema })
const SessionParams = z.strictObject({ sessionId: IdSchema })
const RequestParams = z.strictObject({ sessionId: IdSchema, requestId: z.string().min(1).max(2_000) })
const WebhookParams = z.strictObject({ webhookId: IdSchema })
const WebhookEventSchema = z.enum(['completion', 'attention'])
const AgentWebhookSchema = z.strictObject({
  id: IdSchema,
  taskId: IdSchema.nullable(),
  url: z.string().url(),
  events: z.array(WebhookEventSchema),
  enabled: z.boolean(),
  createdAt: z.number().int(),
  updatedAt: z.number().int(),
})
const AgentWebhookDeliverySchema = z.strictObject({
  id: IdSchema,
  webhookId: IdSchema,
  eventId: IdSchema,
  eventType: WebhookEventSchema,
  status: z.enum(['pending', 'retrying', 'delivered', 'failed']),
  attempt: z.number().int().nonnegative(),
  nextAttemptAt: z.number().int(),
  responseStatus: z.number().int().nullable(),
  error: z.string().nullable(),
  createdAt: z.number().int(),
  deliveredAt: z.number().int().nullable(),
})

export function buildAgentsPublicApi(runtime: ManagedAgentRuntime): PluginApiContribution {
  return {
    pluginId: PLUGIN,
    events: [
      defineEvent({
        pluginId: PLUGIN,
        channel: 'agents.event',
        description: 'A normalized managed-agent event was durably committed.',
        schema: PublicAgentEventSchema,
        scope: 'agents:read',
      }),
      defineEvent({
        pluginId: PLUGIN,
        channel: 'agents.deleted',
        description: 'A local managed-agent session was permanently deleted.',
        schema: z.strictObject({ sessionId: IdSchema }),
        scope: 'agents:read',
      }),
      defineEvent({
        pluginId: PLUGIN,
        channel: 'agents.session',
        description: 'A managed-agent session projection changed.',
        schema: PublicAgentSessionSchema,
        scope: 'agents:read',
      }),
    ],
    endpoints: [
      defineEndpoint({
        operationId: 'agents.providers.list',
        pluginId: PLUGIN,
        method: 'GET',
        path: '/providers',
        scope: 'agents:read',
        risk: 'read',
        summary: 'Discover managed-agent providers, health and capabilities',
        response: z.array(PublicAgentProviderSchema),
        handler: async () => (await runtime.providers()).map(({ executable: _executable, ...provider }) => provider),
      }),
      defineEndpoint({
        operationId: 'agents.sessions.list',
        pluginId: PLUGIN,
        method: 'GET',
        path: '/sessions',
        scope: 'agents:read',
        risk: 'read',
        summary: 'List managed-agent sessions',
        query: z.strictObject({
          taskId: IdSchema.optional(),
          workspaceId: IdSchema.optional(),
          attention: z.coerce.boolean().optional(),
          archived: z.coerce.boolean().optional(),
          cursor: z.coerce.number().int().positive().optional(),
          limit: z.coerce.number().int().min(1).max(100).default(50),
        }),
        response: PageSchema(PublicAgentSessionSchema),
        handler: async (_ctx, { query }) => {
          const page = await runtime.store.listSessions(query)
          return { items: page.sessions, nextCursor: page.nextCursor }
        },
      }),
      defineEndpoint({
        operationId: 'agents.sessions.search',
        pluginId: PLUGIN,
        method: 'GET',
        path: '/sessions/search',
        scope: 'agents:read',
        risk: 'read',
        summary: 'Search managed-agent titles, messages, tool summaries and artifact metadata',
        query: z.strictObject({
          q: z.string().trim().min(1).max(500),
          taskId: IdSchema.optional(),
          workspaceId: IdSchema.optional(),
          limit: z.coerce.number().int().min(1).max(100).default(50),
        }),
        response: z.array(PublicAgentSessionSchema),
        handler: (_ctx, { query }) => runtime.store.searchSessions(query.q, query),
      }),
      defineEndpoint({
        operationId: 'agents.sessions.create',
        pluginId: PLUGIN,
        method: 'POST',
        path: '/tasks/:taskId/sessions',
        scope: 'agents:write',
        risk: 'execute',
        summary: 'Create a task-scoped managed-agent session',
        idempotency: 'required',
        params: TaskParams,
        body: PublicCreateAgentSessionSchema,
        response: PublicAgentSessionSchema,
        status: 201,
        handler: (ctx, { params, body }) => runtime.createSession({
          taskId: params.taskId,
          providerId: body.providerId,
          profileId: body.profileId,
          title: body.title,
          kind: 'interactive',
          config: body.config,
        }, ctx.idempotencyKey),
      }),
      defineEndpoint({
        operationId: 'agents.sessions.import-transcript',
        pluginId: PLUGIN,
        method: 'POST',
        path: '/tasks/:taskId/transcript-imports',
        scope: 'agents:write',
        risk: 'write',
        summary: 'Import an Acorn, Claude Code or Codex transcript as read-only local history',
        idempotency: 'required',
        bodyLimitBytes: 11 * 1024 * 1024,
        params: TaskParams,
        body: z.strictObject({
          providerId: z.enum(['claude', 'codex']),
          profileId: z.string().min(1).max(100),
          title: z.string().trim().min(1).max(500).optional(),
          content: z.string().min(1).max(10 * 1024 * 1024),
        }),
        response: PublicAgentSessionSchema,
        status: 201,
        handler: (_ctx, { params, body }) => runtime.importTranscript({
          taskId: params.taskId,
          ...body,
        }),
      }),
      defineEndpoint({
        operationId: 'agents.sessions.get',
        pluginId: PLUGIN,
        method: 'GET',
        path: '/sessions/:sessionId',
        scope: 'agents:read',
        risk: 'read',
        summary: 'Read a managed-agent session, turns, requests and event page',
        params: SessionParams,
        query: z.strictObject({
          afterSeq: z.coerce.number().int().nonnegative().default(0),
          limit: z.coerce.number().int().min(1).max(2_000).default(500),
        }),
        response: PublicAgentSnapshotSchema,
        handler: (_ctx, { params, query }) => runtime.store.snapshot(params.sessionId, query.afterSeq, query.limit),
      }),
      defineEndpoint({
        operationId: 'agents.turns.enqueue',
        pluginId: PLUGIN,
        method: 'POST',
        path: '/sessions/:sessionId/turns',
        scope: 'agents:write',
        risk: 'execute',
        summary: 'Durably enqueue an interactive provider turn',
        idempotency: 'required',
        bodyLimitBytes: 2 * 1024 * 1024 + 64 * 1024,
        params: SessionParams,
        body: PublicEnqueueAgentTurnSchema,
        response: PublicAgentTurnSchema,
        status: 202,
        handler: (ctx, { params, body }) => runtime.enqueueTurn(params.sessionId, {
          input: body.input,
          source: 'automation',
          effectivePolicy: body.effectivePolicy,
          idempotencyKey: ctx.idempotencyKey!,
        }),
      }),
      defineEndpoint({
        operationId: 'agents.turns.cancel',
        pluginId: PLUGIN,
        method: 'POST',
        path: '/sessions/:sessionId/cancel',
        scope: 'agents:write',
        risk: 'execute',
        summary: 'Cancel an active or queued managed-agent turn',
        params: SessionParams,
        body: z.strictObject({ turnId: IdSchema.optional() }),
        response: z.strictObject({ ok: z.literal(true) }),
        handler: async (_ctx, { params, body }) => {
          await runtime.cancelTurn(params.sessionId, body.turnId)
          return { ok: true as const }
        },
      }),
      defineEndpoint({
        operationId: 'agents.turns.patch-queued',
        pluginId: PLUGIN,
        method: 'PATCH',
        path: '/sessions/:sessionId/turns/:turnId',
        scope: 'agents:write',
        risk: 'write',
        summary: 'Edit or reorder a queued managed-agent turn',
        params: z.strictObject({ sessionId: IdSchema, turnId: IdSchema }),
        body: z.strictObject({
          input: z.array(agentInputPartSchema).min(1).max(32).optional(),
          ordinal: z.number().int().nonnegative().optional(),
        }),
        response: PublicAgentTurnSchema,
        handler: (_ctx, { params, body }) =>
          runtime.patchQueuedTurn(params.sessionId, params.turnId, body),
      }),
      defineEndpoint({
        operationId: 'agents.turns.remove-queued',
        pluginId: PLUGIN,
        method: 'DELETE',
        path: '/sessions/:sessionId/turns/:turnId',
        scope: 'agents:write',
        risk: 'write',
        summary: 'Remove a queued managed-agent turn',
        idempotency: 'optional',
        params: z.strictObject({ sessionId: IdSchema, turnId: IdSchema }),
        response: z.strictObject({ ok: z.literal(true) }),
        handler: async (_ctx, { params }) => {
          await runtime.cancelTurn(params.sessionId, params.turnId)
          return { ok: true as const }
        },
      }),
      defineEndpoint({
        operationId: 'agents.requests.resolve',
        pluginId: PLUGIN,
        method: 'POST',
        path: '/sessions/:sessionId/requests/:requestId/resolve',
        scope: 'agents:approve',
        risk: 'execute',
        summary: 'Resolve a provider permission, question, elicitation or workflow gate',
        idempotency: 'required',
        params: RequestParams,
        body: z.strictObject({ resolution: z.unknown() }),
        response: PublicAgentRequestSchema,
        handler: (ctx, { params, body }) =>
          runtime.resolveRequest(params.sessionId, params.requestId, body.resolution, ctx.idempotencyKey!),
      }),
      defineEndpoint({
        operationId: 'agents.sessions.wait',
        pluginId: PLUGIN,
        method: 'GET',
        path: '/sessions/:sessionId/wait',
        scope: 'agents:read',
        risk: 'read',
        summary: 'Wait for readiness, attention, completion or stop',
        params: SessionParams,
        query: z.strictObject({
          afterSeq: z.coerce.number().int().nonnegative().default(0),
          until: z.enum(['ready', 'attention', 'turn_completed', 'stopped']).default('turn_completed'),
          timeoutMs: z.coerce.number().int().min(0).max(30_000).default(30_000),
        }),
        response: PublicAgentSnapshotSchema,
        handler: (_ctx, { params, query }) =>
          runtime.wait(params.sessionId, query.afterSeq, query.until, query.timeoutMs),
      }),
      defineEndpoint({
        operationId: 'agents.sessions.patch',
        pluginId: PLUGIN,
        method: 'PATCH',
        path: '/sessions/:sessionId',
        scope: 'agents:write',
        risk: 'write',
        summary: 'Rename, archive, unarchive or mark a managed-agent session read',
        params: SessionParams,
        body: z.strictObject({
          title: z.string().trim().min(1).max(500).optional(),
          archived: z.boolean().optional(),
          lastReadSeq: z.number().int().nonnegative().optional(),
        }),
        response: PublicAgentSessionSchema,
        handler: (_ctx, { params, body }) => runtime.patchSession(params.sessionId, body),
      }),
      defineEndpoint({
        operationId: 'agents.sessions.fork',
        pluginId: PLUGIN,
        method: 'POST',
        path: '/sessions/:sessionId/fork',
        scope: 'agents:write',
        risk: 'execute',
        summary: 'Fork a managed-agent session using provider-native or explicit context-copy semantics',
        idempotency: 'required',
        params: SessionParams,
        body: z.strictObject({ title: z.string().trim().min(1).max(500).optional() }),
        response: PublicAgentSessionSchema,
        status: 201,
        handler: (_ctx, { params, body }) => runtime.fork(params.sessionId, body.title),
      }),
      defineEndpoint({
        operationId: 'agents.sessions.compact',
        pluginId: PLUGIN,
        method: 'POST',
        path: '/sessions/:sessionId/compact',
        scope: 'agents:write',
        risk: 'execute',
        summary: 'Request provider-native context compaction',
        params: SessionParams,
        body: z.strictObject({}),
        response: z.strictObject({ ok: z.literal(true) }),
        handler: async (_ctx, { params }) => {
          await runtime.compact(params.sessionId)
          return { ok: true as const }
        },
      }),
      defineEndpoint({
        operationId: 'agents.sessions.resume-managed',
        pluginId: PLUGIN,
        method: 'POST',
        path: '/sessions/:sessionId/resume-managed',
        scope: 'agents:write',
        risk: 'execute',
        summary: 'Return the exclusive input-controller lease to Acorn',
        params: SessionParams,
        body: z.strictObject({}),
        response: PublicAgentSessionSchema,
        handler: (_ctx, { params }) => runtime.resumeManaged(params.sessionId),
      }),
      defineEndpoint({
        operationId: 'agents.sessions.verify-imported-resume',
        pluginId: PLUGIN,
        method: 'POST',
        path: '/sessions/:sessionId/verify-imported-resume',
        scope: 'agents:write',
        risk: 'execute',
        summary: 'Verify an imported provider session reference before enabling managed input',
        params: SessionParams,
        body: z.strictObject({}),
        response: PublicAgentSessionSchema,
        handler: (_ctx, { params }) => runtime.verifyImportedResume(params.sessionId),
      }),
      defineEndpoint({
        operationId: 'agents.sessions.handoff-terminal',
        pluginId: PLUGIN,
        method: 'POST',
        path: '/sessions/:sessionId/handoff-terminal',
        scope: 'agents:write',
        risk: 'execute',
        summary: 'Transfer the exclusive input-controller lease to a resumed provider TUI',
        params: SessionParams,
        body: z.strictObject({}),
        response: PublicAgentSessionSchema,
        handler: (_ctx, { params }) => runtime.handoffToTerminal(params.sessionId),
      }),
      defineEndpoint({
        operationId: 'agents.sessions.delete',
        pluginId: PLUGIN,
        method: 'DELETE',
        path: '/sessions/:sessionId',
        scope: 'agents:write',
        risk: 'write',
        summary: 'Permanently delete local managed-agent history and object references',
        idempotency: 'optional',
        params: SessionParams,
        response: z.strictObject({
          local: z.literal('deleted'),
          provider: z.enum(['deleted', 'unsupported', 'failed']),
          detail: z.string().optional(),
        }),
        handler: (_ctx, { params }) => runtime.deleteSession(params.sessionId),
      }),
      defineEndpoint({
        operationId: 'agents.sessions.export',
        pluginId: PLUGIN,
        method: 'GET',
        path: '/sessions/:sessionId/export',
        scope: 'agents:read',
        risk: 'read',
        summary: 'Export complete local managed-agent history',
        params: SessionParams,
        query: z.strictObject({ format: z.enum(['json', 'markdown']).default('json') }),
        response: z.strictObject({ format: z.enum(['json', 'markdown']), content: z.string() }),
        handler: async (_ctx, { params, query }) => ({
          format: query.format,
          content: await runtime.exportSession(params.sessionId, query.format),
        }),
      }),
      defineEndpoint({
        operationId: 'agents.artifacts.list',
        pluginId: PLUGIN,
        method: 'GET',
        path: '/sessions/:sessionId/artifacts',
        scope: 'agents:read',
        risk: 'read',
        summary: 'List large artifacts stored outside the event ledger',
        params: SessionParams,
        response: z.array(PublicAgentArtifactSchema),
        handler: (_ctx, { params }) => runtime.artifacts.list(params.sessionId),
      }),
      defineEndpoint({
        operationId: 'agents.webhooks.list',
        pluginId: PLUGIN,
        method: 'GET',
        path: '/webhooks',
        scope: 'agents:read',
        risk: 'read',
        summary: 'List signed agent completion and attention webhooks',
        response: z.array(AgentWebhookSchema),
        handler: () => runtime.webhooks.list(),
      }),
      defineEndpoint({
        operationId: 'agents.webhooks.create',
        pluginId: PLUGIN,
        method: 'POST',
        path: '/webhooks',
        scope: 'agents:write',
        risk: 'write',
        summary: 'Create a signed agent completion or attention webhook',
        idempotency: 'required',
        body: z.strictObject({
          taskId: IdSchema.optional(),
          url: z.string().url().max(2_000),
          events: z.array(WebhookEventSchema).min(1).max(2),
        }),
        response: z.strictObject({
          webhook: AgentWebhookSchema,
          signingSecret: z.string(),
        }),
        status: 201,
        handler: (_ctx, { body }) => runtime.webhooks.create(body),
      }),
      defineEndpoint({
        operationId: 'agents.webhooks.patch',
        pluginId: PLUGIN,
        method: 'PATCH',
        path: '/webhooks/:webhookId',
        scope: 'agents:write',
        risk: 'write',
        summary: 'Enable, disable or change events for an agent webhook',
        params: WebhookParams,
        body: z.strictObject({
          enabled: z.boolean().optional(),
          events: z.array(WebhookEventSchema).min(1).max(2).optional(),
        }),
        response: AgentWebhookSchema,
        handler: (_ctx, { params, body }) => runtime.webhooks.patch(params.webhookId, body),
      }),
      defineEndpoint({
        operationId: 'agents.webhooks.delete',
        pluginId: PLUGIN,
        method: 'DELETE',
        path: '/webhooks/:webhookId',
        scope: 'agents:write',
        risk: 'write',
        summary: 'Delete an agent webhook and its delivery log',
        params: WebhookParams,
        response: z.strictObject({ ok: z.literal(true) }),
        handler: async (_ctx, { params }) => {
          await runtime.webhooks.remove(params.webhookId)
          return { ok: true as const }
        },
      }),
      defineEndpoint({
        operationId: 'agents.webhooks.deliveries',
        pluginId: PLUGIN,
        method: 'GET',
        path: '/webhooks/:webhookId/deliveries',
        scope: 'agents:read',
        risk: 'read',
        summary: 'Inspect bounded signed-webhook delivery attempts',
        params: WebhookParams,
        query: z.strictObject({
          limit: z.coerce.number().int().min(1).max(200).default(100),
        }),
        response: z.array(AgentWebhookDeliverySchema),
        handler: (_ctx, { params, query }) =>
          runtime.webhooks.deliveries(params.webhookId, query.limit),
      }),
    ],
  }
}
